# local_backend: true
backend:
  name: git-gateway
  repo: https://github.com/daresaydigital/KOLL
  branch: main
site_url: https://koll-app.netlify.app/
publish_mode: editorial_workflow
media_folder: src/assets/
collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }